# Generated by Django 3.2 on 2022-05-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_contactus_newsletter'),
        ('checkout', '0007_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
