# Generated by Django 4.0.4 on 2022-05-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_reviews_review_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='category',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='category',
            new_name='product',
        ),
    ]
